/**
 * Interface defining the contract for an Embedding Provider.
 * This establishes a clean boundary between the core RAG application logic and
 * the specific LLM/embedding API provider (e.g., Gemini, OpenAI, Cohere).
 */
export interface EmbeddingProvider {
  /**
   * Generates a vector embedding for a single text input.
   * 
   * @param text The input text string to generate an embedding for.
   * @returns A promise that resolves to the high-dimensional vector array.
   */
  embed(text: string): Promise<number[]>;

  /**
   * Generates vector embeddings for a list of text inputs.
   * This is optimized for processing multiple documents in batch sequences.
   * 
   * @param texts An array of input text strings.
   * @returns A promise that resolves to an array of high-dimensional vector arrays.
   */
  embedBatch(texts: string[]): Promise<number[][]>;

  /**
   * Returns the configuration identifier string for the model being used.
   */
  getModelName(): string;

  /**
   * Returns the vector dimension size generated by this model (e.g., 768).
   */
  getDimensions(): number;
}
